name: Build and Package Vite + Vue NPM Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build with Vite
        run: |
          npm run build

      - name: Package dist as ZIP
        run: |
          zip -r dist.zip dist/

      - name: Upload ZIP as Artifact (using v2)
        uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.node-version }}
          path: dist/
